# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0002_auto_20170317_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='address',
        ),
        migrations.AddField(
            model_name='localization',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
