# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0004_auto_20170317_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
