# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0005_delete_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtype',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
