# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0007_auto_20170319_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmactuator',
            options={'verbose_name_plural': 'AlarmActuators'},
        ),
        migrations.AlterModelOptions(
            name='subscription_group',
            options={'verbose_name_plural': 'Subscription_Groups'},
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='subscription',
        ),
    ]
