# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0008_auto_20170321_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggered_alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AC', 'Active'), ('NS', 'Not Seen'), ('SE', 'Seen')], max_length=2)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainserver.Alarm')),
                ('value', models.ManyToManyField(to='mainserver.Value')),
            ],
        ),
        migrations.AlterField(
            model_name='day_week',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
    ]
