# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0009_auto_20170326_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='max_min',
            new_name='max',
        ),
    ]
