# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0010_auto_20170326_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='daysOfWeek',
            field=models.ManyToManyField(blank=True, null=True, to='mainserver.day_week'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='daysOfYear',
            field=models.ManyToManyField(blank=True, null=True, to='mainserver.day_year'),
        ),
    ]
