# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import server.mainserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0013_auto_20170326_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='daysOfYear',
        ),
        migrations.AddField(
            model_name='alarm',
            name='beg_dayOfYear',
            field=models.DateTimeField(blank=True, null=True, verbose_name=server.mainserver.models.day_year),
        ),
        migrations.AddField(
            model_name='alarm',
            name='end_dayOfYear',
            field=models.DateTimeField(blank=True, null=True, verbose_name=server.mainserver.models.day_year),
        ),
    ]
