# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0014_auto_20170326_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='beg_dayOfYear',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='end_dayOfYear',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_week',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('S', 'Sunday')], max_length=1),
        ),
    ]
