# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0015_auto_20170326_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='beg_dayOfYear',
            new_name='beg_date',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='end_dayOfYear',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='max',
        ),
        migrations.AddField(
            model_name='alarm',
            name='type_alarm',
            field=models.CharField(choices=[('MAX', 'Maximum'), ('MIN', 'Minimum')], default='MAX', max_length=3),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='hours_active_beg',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='hours_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
