# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0017_auto_20170326_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='name',
            field=models.TextField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.TextField(default='Unknown', max_length=50, unique=True),
        ),
    ]
