# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0022_auto_20170411_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='state',
            field=models.CharField(choices=[('AC', 'Active'), ('DE', 'Deleted')], default='AC', max_length=2),
        ),
    ]
