# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0026_auto_20170420_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmactuator',
            name='alarm',
        ),
        migrations.AddField(
            model_name='alarmactuator',
            name='alarm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainserver.Alarm'),
        ),
        migrations.RemoveField(
            model_name='alarmactuator',
            name='subscription',
        ),
        migrations.AddField(
            model_name='alarmactuator',
            name='subscription',
            field=models.ManyToManyField(blank=True, to='mainserver.Subscription'),
        ),
    ]
