# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0028_auto_20170420_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='has_threshold',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
