# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0029_auto_20170425_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='type_alarm',
            field=models.CharField(blank=True, choices=[('MAX', 'Maximum'), ('MIN', 'Minimum')], default='MAX', max_length=3, null=True),
        ),
    ]
