# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0030_auto_20170425_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainserver.Subscription'),
        ),
    ]
