# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0031_auto_20170425_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='metric',
            new_name='subscription',
        ),
    ]
