# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0032_auto_20170425_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
