# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0038_auto_20170425_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='working_state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('WI', 'Working on it'), ('SO', 'Solved')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='state',
            field=models.CharField(choices=[('NS', 'Not Seen'), ('SE', 'Seen')], max_length=2),
        ),
    ]
