# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0046_auto_20170428_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
