# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0048_reportattach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportattach',
            options={'verbose_name_plural': 'Report Attachments'},
        ),
        migrations.AlterModelOptions(
            name='triggered_alarm',
            options={'verbose_name_plural': 'Triggered_Alarms'},
        ),
        migrations.AddField(
            model_name='userreport',
            name='attach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainserver.ReportAttach'),
        ),
    ]
