# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0049_auto_20170505_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='attach',
        ),
        migrations.AddField(
            model_name='userreport',
            name='attach',
            field=models.ManyToManyField(to='mainserver.ReportAttach'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='working_state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('WI', 'Working On'), ('SO', 'Solved')], default='WA', max_length=2),
        ),
    ]
