# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0051_auto_20170513_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ('date_created',), 'verbose_name': 'Alert', 'verbose_name_plural': 'Alarms'},
        ),
        migrations.AlterModelOptions(
            name='alarmactuator',
            options={'verbose_name': 'Actuator of Alert', 'verbose_name_plural': 'Actuators of Alert'},
        ),
        migrations.AlterModelOptions(
            name='day_year',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.AlterModelOptions(
            name='localization',
            options={'verbose_name': 'Localization', 'verbose_name_plural': 'Localizations'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('date_beginning',), 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='reportattach',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Report Attachments'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('date_added',), 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('date_added',), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscription_group',
            options={'verbose_name': 'Subscription Group', 'verbose_name_plural': 'Subscription Groups'},
        ),
        migrations.AlterModelOptions(
            name='triggered_alarm',
            options={'verbose_name': 'Triggered Alarm', 'verbose_name_plural': 'Triggered Alarms'},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ('date',), 'verbose_name': 'Citizen Report', 'verbose_name_plural': 'Citizen Reports'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('date',), 'verbose_name': 'Value from stream', 'verbose_name_plural': 'Values from Streams'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='state',
            field=models.CharField(choices=[('NS', 'Not Seen'), ('SE', 'Seen')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('NS', 'Not Seen'), ('SE', 'Seen')], max_length=2),
        ),
    ]
