# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0053_auto_20170513_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
