# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0054_userreport_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggered_alarm',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
